### ISSUE TITLE
如何添加子级 同级 删除当前节点

### ISSUE THREAD

**Issue by zhanjunhao** [mafengwo/vue-drag-tree-table#12]
有个需求就是可以 对树形表格当前行的数据 进行增删查改 😂  这个要如何去做😎

**Comment by ColdDay** [comment]
> 有个需求就是可以 对树形表格当前行的数据 进行增删查改 😂 这个要如何去做😎
每一行增加增删改查按钮，点击按钮的回调函数中会返回当前行的数据
有两种方案：1.提交当前行ID给后端，执行完操作后返回全量数据重新渲染。2.本地操作数据，最后操作完全量提交，这里需要递归数据进行处理

**Comment by zhanjunhao** [comment]
需求是产品经理要求这样的
![FN00XRH)ORZ`7KK16TIW%(8](https://user-images.githubusercontent.com/25976993/56007818-960dfa80-5d0c-11e9-9278-70a8a16409e0.png)
目前 添加子级问题 已反馈到element-ui 官方 删除节点是没问题的 谢谢你的方案

**Comment by ColdDay** [comment]
> 需求是产品经理要求这样的
> 
> ![QQ截图20190412102000](https://user-images.githubusercontent.com/25976993/56007927-fc931880-5d0c-11e9-8fd4-d986afab31d1.png)
> 
> Bug预览图
> ![FN00XRH)ORZ`7KK16TIW%(8](https://user-images.githubusercontent.com/25976993/56007818-960dfa80-5d0c-11e9-9278-70a8a16409e0.png)
> codeUrl: https://codepen.io/zhanjunhao/pen/JVJRVO
> 
> 目前 添加子级问题 已反馈到element-ui 官方 删除节点是没问题的 谢谢你的方案

为什么不用弹窗编辑呢？满屏都是输入框交互不太友好

**Comment by zhanjunhao** [comment]
额 我也想

**Comment by ColdDay** [comment]
> 额 我也想

强势一点，给怼回去😄

**Comment by zhanjunhao** [comment]
ヽ(￣▽￣)و 我试试
