### ISSUE TITLE
点击后边的编辑获取当前行index

### ISSUE THREAD

**Issue by banboluli** [mafengwo/vue-drag-tree-table#13]
原谅我这个菜鸡，百思不得其解，在删除事件里获取这行的index，取的值总是-1
这是cloumn里的删除事件：
`actions: [{
                          	text: '删除',
                          	onclick: this.delParameter,
                          	formatter: (index) => {
                            	return '<i>删除 </i>'
                          	}
                          	
	                    }`
删除事件是这么写得：
`delParameter(index){
  var rowIndex = $(this).parents(".tree-row").attr("tree-id").index();
  console.log(rowIndex);
}`

**Comment by ColdDay** [comment]
> 原谅我这个菜鸡，百思不得其解，在删除事件里获取这行的index，取的值总是-1
> 这是cloumn里的删除事件：
> `actions: [{
> text: '删除',
> onclick: this.delParameter,
> formatter: (index) => {
> return '删除 '
> }
> 
> ```
>                     }`
> ```
> 删除事件是这么写得：
> `delParameter(index){ var rowIndex = $(this).parents(".tree-row").attr("tree-id").index(); console.log(rowIndex); }`

delParameter(index) 这里index参数是row对象，不是索引，对象里面有row.order可以当作index使用

**Comment by banboluli** [comment]
> > 原谅我这个菜鸡，百思不得其解，在删除事件里获取这行的index，取的值总是-1
> > 这是cloumn里的删除事件：
> > `actions: [{
> > text: '删除',
> > onclick: this.delParameter,
> > formatter: (index) => {
> > return '删除 '
> > }
> > ```
> >                     }`
> > ```
> > 删除事件是这么写得：
> > `delParameter(index){ var rowIndex = $(this).parents(".tree-row").index(); console.log(rowIndex); }`
> 
> delParameter(index) 这里index参数是row对象，不是索引，对象里面有row.order可以当作index使用



> > 原谅我这个菜鸡，百思不得其解，在删除事件里获取这行的index，取的值总是-1
> > 这是cloumn里的删除事件：
> > `actions: [{
> > text: '删除',
> > onclick: this.delParameter,
> > formatter: (index) => {
> > return '删除 '
> > }
> > ```
> >                     }`
> > ```
> > 删除事件是这么写得：
> > `delParameter(index){ var rowIndex = $(this).parents(".tree-row").attr("tree-id").index(); console.log(rowIndex); }`
> 
> delParameter(index) 这里index参数是row对象，不是索引，对象里面有row.order可以当作index使用
谢谢您的回复
