### ISSUE TITLE
点击编辑获取当前以及父级的信息

### ISSUE THREAD

**Issue by krayshaw** [mafengwo/vue-drag-tree-table#16]
点击编辑怎么获取当前以及父节点的信息

**Comment by ColdDay** [comment]
> 点击编辑怎么获取当前以及父节点的信息
` onclick` 事件唯一参数是当前节点信息，至于获取父节点信息目前插件暂不提供，如有需求可以支持

[https://github.com/mafengwo/vue-drag-tree-table/issues/13](url)

**Comment by krayshaw** [comment]
谢谢，我已经解决了

**Comment by ColdDay** [comment]
> 谢谢，我已经解决了

怎么解决的？

**Comment by krayshaw** [comment]
递归数据，进行if判断
 
------------------
前面有很长的路要走,我一定不可以倒下


 




------------------ 原始邮件 ------------------
发件人: "carr_y"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 上午10:14
收件人: "mafengwo/vue-drag-tree-table"<vue-drag-tree-table@noreply.github.com>; 
抄送: "肖媛媛"<916286541@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mafengwo/vue-drag-tree-table] 点击编辑获取当前以及父级的信息 (#16)



 
谢谢，我已经解决了
  
怎么解决的？

**Comment by ColdDay** [comment]
> 递归数据，进行if判断
> […](#)
> ------------------ 前面有很长的路要走,我一定不可以倒下
> ------------------ 原始邮件 ------------------ 发件人: "carr_y"<notifications@github.com>; 发送时间: 2019年5月28日(星期二) 上午10:14 收件人: "mafengwo/vue-drag-tree-table"<vue-drag-tree-table@noreply.github.com>; 抄送: "肖媛媛"<916286541@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [mafengwo/vue-drag-tree-table] 点击编辑获取当前以及父级的信息 (#16) 谢谢，我已经解决了 怎么解决的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的
