### ISSUE TITLE
表格能否加复选框

### ISSUE THREAD

**Issue by iceAcmen** [mafengwo/vue-drag-tree-table#17]
用于选中当前行

**Comment by ColdDay** [comment]
> 用于选中当前行
本身支持自定义内容的，你可以用下面这种方式添加复选框
{
   title: '菜单名称',
   field: 'name',
   width: 200,
   align: 'center',
   formatter: (item) => {
     return '<checkbox>'+item.name+'</checkbox>'
   }
 },

**Comment by iceAcmen** [comment]
> > 用于选中当前行
> > 本身支持自定义内容的，你可以用下面这种方式添加复选框
> > {
> > title: '菜单名称',
> > field: 'name',
> > width: 200,
> > align: 'center',
> > formatter: (item) => {
> > return ''+item.name+''
> > }
> > },

表头不支持自定义吧？这种方法无法在表头添加“全选”框

**Comment by ColdDay** [comment]
> > > 用于选中当前行
> > > 本身支持自定义内容的，你可以用下面这种方式添加复选框
> > > {
> > > title: '菜单名称',
> > > field: 'name',
> > > width: 200,
> > > align: 'center',
> > > formatter: (item) => {
> > > return ''+item.name+''
> > > }
> > > },
> 
> 表头不支持自定义吧？这种方法无法在表头添加“全选”框
嗯，可以考虑增加checkbox类型的列，下个版本加上吧

**Comment by ColdDay** [comment]
1.2.2版本试一下,将type设置checkbox，这一列就变成checkbox，勾选时会触发onChange,参数是所有选中的数组集合，如下：

      {
        type: "checkbox",
        title: "链接",
        field: "uri",
        width: 80,
        align: "center",
        onChange: this.onCheckChange
      },


onCheckChange(rows) {

}

**Comment by iceAcmen** [comment]
> 1.2.2版本试一下,将type设置checkbox，这一列就变成checkbox，勾选时会触发onChange,参数是所有选中的数组集合，如下：
> 
> ```
>   {
>     type: "checkbox",
>     title: "链接",
>     field: "uri",
>     width: 80,
>     align: "center",
>     onChange: this.onCheckChange
>   },
> ```
> 
> onCheckChange(rows) {
> 
> }

可以，很强大，赞一个
