### ISSUE TITLE
checkbox在勾选拥有子集的节点,会把子节点也一起勾选上返回在onchange

### ISSUE THREAD

**Issue by JesseWeb** [mafengwo/vue-drag-tree-table#18]
能否在type为checkbox的column中,加上一个标识[isContainChildren]用于控制是否勾选子节点

**Comment by ColdDay** [comment]
> 能否在type为checkbox的column中,加上一个标识[isContainChildren]用于控制是否勾选子节点

可以，我今天加上

**Comment by JesseWeb** [comment]
非常感谢你对生产环境做出的贡献

**Comment by ColdDay** [comment]
> 非常感谢你对生产环境做出的贡献

1.2.3版本已支持，默认不选中子节点
{
    type: 'checkbox',
    isContainChildren: true, //是否勾选子节点，默认false
    onChange: this.onCheck, // parmas selectRows
    title: '链接',
    field: 'url',
    width: 200,
    align: 'center'
  },

**Comment by JesseWeb** [comment]
全选没有被isContainChildren控制
