### ISSUE TITLE
全选没有被isContainChildren控制

### ISSUE THREAD

**Issue by JesseWeb** [mafengwo/vue-drag-tree-table#19]
全选没有被isContainChildren控制

_Originally posted by @JesseWeb in https://github.com/mafengwo/vue-drag-tree-table/issues/18#issuecomment-496368552_

**Comment by ColdDay** [comment]
> 全选没有被isContainChildren控制
> 
> _Originally posted by @JesseWeb in [#18 (comment)](https://github.com/mafengwo/vue-drag-tree-table/issues/18#issuecomment-496368552)_

全选需要控制吗？感觉全选就是选全部啊

**Comment by JesseWeb** [comment]
全选:
A.当前视觉下的全部item的全选(user视角)(业务场景居多);
B.所有数据全选(developer视角);

照顾两方的视角我觉得可以控制

**Comment by JesseWeb** [comment]
同时这样会让组件使用场景更广泛

**Comment by ColdDay** [comment]
> 全选:
> A.当前视觉下的全部item的全选(user视角)(业务场景居多);
> B.所有数据全选(developer视角);
> 
> 照顾两方的视角我觉得可以控制

这个当前视觉理解有问题，你指的手机当前视觉是可见的行对吗？收起来的不算，但是这样的话层级较多，展开某一层时，点击全选是选第一层呢？还是所有可见的行

**Comment by ColdDay** [comment]
[
 {
   "id":40,
   "parent_id":0,
   "order":0,
   "name":"动物类",
   "uri":"/masd/ds",
   "open":true,
   "lists":[]
 },{
   "id":5,
   "parent_id":0,
   "order":1,
   "name":"昆虫类",
   "uri":"/masd/ds",
   "open":true,
   "isShowCheckbox": false, '如果设置了type=checkbox,但是想控制某些行不显示CheckBox，可以用此属性'
   "lists":[
     {
       "id":12,
       "parent_id":5,
       "open":true,
       "order":0,
       "name":"蚂蚁",
       "uri":"/masd/ds",
       "lists":[]
     }
   ]
 },
 {
   "id":19,
   "parent_id":0,
   "order":2,
   "name":"植物类",
   "uri":"/masd/ds",
   "open":true,
   "lists":[]
 }
]

如果不想让某些行显示CheckBox或者不勾选它，可以设置isShowCheckbox自行控制
