### ISSUE TITLE
onTreeDataChange

### ISSUE THREAD

**Issue by Murraya-paniculata** [mafengwo/vue-drag-tree-table#20]
希望能拿到targetID和dragId。在onTreeDataChange中给到我。另外希望参与这个项目,嘻嘻

**Comment by ColdDay** [comment]
> 希望能拿到targetID和dragId。在onTreeDataChange中给到我。另外希望参与这个项目,嘻嘻

欢迎加入

**Comment by ColdDay** [comment]
所以你可以帮我完善文档和demo对吗^_^

**Comment by Murraya-paniculata** [comment]
可以的。

**Comment by ColdDay** [comment]
> 可以的。

可以加我微信，cold_daywx

**Comment by ColdDay** [comment]
1.2.4版本，拖拽参数已经添加，使用方式如下
```
    // list:更新后的数据源
    // from: 当前被拖拽的行
    // to: 目标拖拽行
    // where: 拖拽的类型，top（上面）、center（里面）、bottom（下面）
    onTreeDataChange(list, from, to, where) {
      console.log(from, to, where);
      this.treeData.lists = list;
    }
```

**Comment by IcarusSky** [comment]
![image](https://user-images.githubusercontent.com/25057405/63234674-f556bb00-c268-11e9-99c4-12fbf17cff6b.png)
您好，这个参数有点奇怪，为什么这里已经是变化后的parent_id，而不是变化前的parent_id
