### ISSUE TITLE
想问一下如何实现两个vue-drag-tree-table组件的互相拖拽吗

### ISSUE THREAD

**Issue by sixgay** [mafengwo/vue-drag-tree-table#21]

**Comment by ColdDay** [comment]
怎么会有这种需求？？

**Comment by sixgay** [comment]
刚好就是有这种需要....,只要是用来实现权限的配置,一个组件是存放已经配置的好路由权限,一个组件是存放等待配置的路由权限,通过拖拽等待配置权限的组件内的row,可以移动到另外一个组件的row里面.....

**Comment by ColdDay** [comment]
那你这个是树形的吗？如果不是可以用穿梭框组件的 ，比如element的组件[https://element.eleme.cn/#/zh-CN/component/transfer](url)

**Comment by sixgay** [comment]
我的也是表格树形可拖拽的,我自己想想怎么实现.
还有个问题是:custom_field对象里面的id的值现在是可以自定义的嘛,存在的一些bug就是您的row.vue里面有些地方直接写了model.id应该要写成model[custom_field.id],这样我才能实现它的自定义

**Comment by ColdDay** [comment]
> 我的也是表格树形可拖拽的,我自己想想怎么实现.
> 还有个问题是:custom_field对象里面的id的值现在是可以自定义的嘛,存在的一些bug就是您的row.vue里面有些地方直接写了model.id应该要写成model[custom_field.id],这样我才能实现它的自定义

之前不支持自定义的，后来加的，id这块可能漏掉了，我看下

**Comment by ColdDay** [comment]
id自定义问题1.2.4版本已修改，感谢反馈
