### ISSUE TITLE
表格设置了最大高度，内容滚动显示时，滚动到下面能否冻结表头标题？

### ISSUE THREAD

**Issue by iceAcmen** [mafengwo/vue-drag-tree-table#22]
表格内容向下滚动之后，就看不见标题了，能否将标题做成像Excel一样的可以冻结窗格

**Comment by ColdDay** [comment]
> 表格内容向下滚动之后，就看不见标题了，能否将标题做成像Excel一样的可以冻结窗格
可以，我加上这个功能，这两天发下个版本

**Comment by iceAcmen** [comment]
> > 表格内容向下滚动之后，就看不见标题了，能否将标题做成像Excel一样的可以冻结窗格
> > 可以，我加上这个功能，这两天发下个版本

还有两个建议，列宽支持鼠标拖动调整，以及如果列宽太窄内容显示不全的话鼠标悬浮显示完整内容，希望采纳

**Comment by iceAcmen** [comment]
> > 表格内容向下滚动之后，就看不见标题了，能否将标题做成像Excel一样的可以冻结窗格
> > 可以，我加上这个功能，这两天发下个版本

另外，有没有办法可以对不同层级的单元格设置不同的样式（例如背景颜色）以区分显示

**Comment by ColdDay** [comment]
1.2.4支持固定表头，使用如下
```html
<dragTreeTable
:data="treeData"
:onDrag="onTreeDataChange"
:fixed="true"
:height="300"
:isdraggable="true"></dragTreeTable>
```

不同层级展示颜色不一样需自己写样式，目前插件已经在每一行增加data-level属性，可自行按照层级设置颜色

**Comment by ColdDay** [comment]
> 还有两个建议，列宽支持鼠标拖动调整，以及如果列宽太窄内容显示不全的话鼠标悬浮显示完整内容，希望采纳

鼠标悬浮显示全部内容，插件本身支持自定内容，可以再formatter中内容标签增加title属性
