### ISSUE TITLE
能否增加一个配置项，同级之间只能切换前后位置不能改变包含关系

### ISSUE THREAD

**Issue by DraeneiYong** [mafengwo/vue-drag-tree-table#26]

**Comment by ColdDay** [comment]
可以考虑增加这种配置，下个版本加上

**Comment by ColdDay** [comment]
> _No description provided._

升级2.0.1版本，增加了该功能，通过onlySameLevelCanDrag=true控制，具体效果查看demohttps://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E7%A6%81%E6%AD%A2%E6%8B%96%E6%8B%BD%E6%94%B9%E5%8F%98%E5%B1%82%E7%BA%A7%EF%BC%8C%E5%8F%AA%E5%85%81%E8%AE%B8%E8%B0%83%E6%95%B4%E9%A1%BA%E5%BA%8F
