### ISSUE TITLE
当前表格如果出现了滚动条，且滚动最底部

### ISSUE THREAD

**Issue by pangchao21** [mafengwo/vue-drag-tree-table#28]
当前表格如果出现了滚动条，且滚动最底部，这时拖拽就会出现拖拽的焦点和鼠标错位的现象，这个bug有解决方案了吗

**Comment by ColdDay** [comment]
> 当前表格如果出现了滚动条，且滚动最底部，这时拖拽就会出现拖拽的焦点和鼠标错位的现象，这个bug有解决方案了吗

这个问题早就解决了的，你更新最新版1.2.5试试

**Comment by dellenshang** [comment]
是的，最新版本也是一样，
是不固定不设置高度的时候，随着页面滚动
这时只要**鼠标滚动后**再抓起任何一个节点开始拖动，就会出现焦点和鼠标错位的现象

**Comment by FullOfVigour** [comment]
尝试了固定高度但不加fixed，无效
fixed属性应该加在哪一层？

**Comment by ColdDay** [comment]
2.0.8修复了此问题，改用getBoundingClientRect计算元素位置，请升级后使用
