### ISSUE TITLE
> 怎么看不到1.17的版本呢

### ISSUE THREAD

**Issue by pangchao21** [mafengwo/vue-drag-tree-table#29]
> 怎么看不到1.17的版本呢

用最新版吧1.2.5

我现在用的是这个1.2.5的版本，还是存在这个问题，没有更新最新的代码吗？

**Comment by ColdDay** [comment]
> > 怎么看不到1.17的版本呢
> 
> 用最新版吧1.2.5
> 
> 我现在用的是这个1.2.5的版本，还是存在这个问题，没有更新最新的代码吗？

什么浏览器？有可以访问的地址可以看吗

**Comment by pangchao21** [comment]
谷歌浏览器，目前还是部署在内网，您应该访问不到，我看了下源码，还没用那个scrollTop，还是用的offetTop
