### ISSUE TITLE
formatter里面是否能渲染自定义组件呢

### ISSUE THREAD

**Issue by dellenshang** [mafengwo/vue-drag-tree-table#31]
```js
formatter: item => {
              return `<i-table></i-table>`
            }
```
像这样的，我每行想要渲染自定义的或者ele，iview的组件，请问该怎么做呢

**Comment by ColdDay** [comment]
> ```js
> formatter: item => {
>               return `<i-table></i-table>`
>             }
> ```
> 
> 像这样的，我每行想要渲染自定义的或者ele，iview的组件，请问该怎么做呢

目前不支持，只支持html字符串
