### ISSUE TITLE
为什么用npm下载完后,正常引入后,系统提示dragTreeTable在module找不到????

### ISSUE THREAD

**Issue by 609587174** [mafengwo/vue-drag-tree-table#35]

**Comment by nkcc** [comment]
我的也是这个错误

* dragTreeTable in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!

**Comment by nkcc** [comment]
把import 改成这个就可以了 import dragTreeTable from 'drag-tree-table' 
示例中是驼峰命名导致无法找到
