### ISSUE TITLE
关于操作栏的一些 疑问

### ISSUE THREAD

**Issue by FullOfVigour** [mafengwo/vue-drag-tree-table#39]
![image](https://user-images.githubusercontent.com/25943199/65619224-5b65f900-dff2-11e9-9afa-0920a7c82fb5.png)

如图所示，当前写法是不会报错的。
但是当我把formatter删除之后会报formatter不是一个方法的错误，如此看来formatter是一个必填参数，那和上面的text是否有一些重复性了？

小白刚开始学，不太懂大佬您的想法，望解答，谢谢

**Comment by ColdDay** [comment]
嗯，从组件开发角度这个是有问题的，当时主要考虑操作栏都是有交互的，样式肯定跟普通栏不一样，而且需要添加事件，这两个必须要在formatter 中才可以完成的，如果单单早普通展示，不需要用action



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐晗 <notifications@github.com&gt;
发送时间: 2019年9月26日 00:15
收件人: mafengwo/vue-drag-tree-table <vue-drag-tree-table@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mafengwo/vue-drag-tree-table] 关于操作栏的一些 疑问 (#39)






如图所示，当前写法是不会报错的。
但是当我把formatter删除之后会报formatter不是一个方法的错误，如此看来formatter是一个必填参数，那和上面的text是否有一些重复性了？

小白刚开始学，不太懂大佬您的想法，望解答，谢谢

**Comment by FullOfVigour** [comment]
谢谢大神指导，然后最近我又发现一个小问题，当类型为selection时会出现不居中的情况
![image](https://user-images.githubusercontent.com/25943199/65931389-07b53e80-e43c-11e9-9f11-2da749aa32a7.png)

**Comment by FullOfVigour** [comment]
根据元素可以看到大概是因为折叠的icon占了一点位置
![image](https://user-images.githubusercontent.com/25943199/65931431-287d9400-e43c-11e9-9a32-c8e26a90edbb.png)
请问这种情况该如何解决？

**Comment by ColdDay** [comment]
看一下type是怎么用的，selection 不要乱用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐晗 <notifications@github.com&gt;
发送时间: 2019年10月1日 11:10
收件人: mafengwo/vue-drag-tree-table <vue-drag-tree-table@noreply.github.com&gt;
抄送: carr_y <1747581091@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mafengwo/vue-drag-tree-table] 关于操作栏的一些 疑问 (#39)




谢谢大神指导，然后最近我又发现一个小问题，当类型为selection时会出现不居中的情况

**Comment by FullOfVigour** [comment]
我看到这边type是三个可选值，
![image](https://user-images.githubusercontent.com/25943199/65931608-fde00b00-e43c-11e9-80e6-5c3bd6252ec6.png)shi是不是说只有用到才去选择这个值，不用的话就空着就好是吗？

**Comment by ColdDay** [comment]
默认就行，这个文档我修正下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐晗 <notifications@github.com&gt;
发送时间: 2019年10月1日 11:17
收件人: mafengwo/vue-drag-tree-table <vue-drag-tree-table@noreply.github.com&gt;
抄送: carr_y <1747581091@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mafengwo/vue-drag-tree-table] 关于操作栏的一些 疑问 (#39)




我看到这边type是三个可选值，
 shi是不是说只有用到才去选择这个值，不用的话就空着就好是吗？

**Comment by FullOfVigour** [comment]
好的，谢谢
