### ISSUE TITLE
当表格内容较多，页面出现滚动条时，拖动的显示会在非鼠标指示区域

### ISSUE THREAD

**Issue by stzhongjie** [mafengwo/vue-drag-tree-table#4]

**Comment by ColdDay** [comment]
更新一下组件到1.16版本试试，这个问题我已经修复了

**Comment by stzhongjie** [comment]
<img width="742" alt="111" src="https://user-images.githubusercontent.com/10415868/50136132-b3d4d100-02d1-11e9-8a25-e75f16a5da29.png">
你好，更新过了，并不是那个无法滚动的原因。
而是：当有滚动条，并向下滚动了，我按住下方某一条数据，会发现拖拽条出现在上面，距离和滚动条距离一致。具体如上图。
谢谢解答！

**Comment by stzhongjie** [comment]
是否因为 getElementTop 这个函数里面是用 offsetTop 而不是 scrollTop，忽略了表格可能有滚动条

**Comment by stzhongjie** [comment]
getElementTop(element) {
        let scrollTop = document.getElementsByClassName('cList')[0].scrollTop
        var actualTop = element.offsetTop - scrollTop;
        var current = element.offsetParent;
        while (current !== null) {
          actualTop += current.offsetTop;
          current = current.offsetParent;
        }
        return actualTop
      }

刚试了一下，稍微改一下这个函数，减掉表格框的scrollTop即可

再次感谢作者的组件！

**Comment by ColdDay** [comment]
多谢提醒，我的确忽略了这种情况，我会按照你写的方式更新一下，谢谢

**Comment by ColdDay** [comment]
已经更新，1.17版本修复此问题，如果表格需要在固定区域内滚动，表格直接父元素设置overflow:scroll，不支持跨级设置，插件会获取当前表格的父元素scrollTop匹配
举例
<div id="app">
  <dragTreeTable :data="treeData" :onDrag="onTreeDataChange"></dragTreeTable>
  </div>
<style>
#app {
  height: 400px;
  overflow: scroll;
}
</style>

**Comment by pangchao21** [comment]
怎么看不到1.17的版本呢

**Comment by ColdDay** [comment]
> 怎么看不到1.17的版本呢

用最新版吧1.2.5

**Comment by pangchao21** [comment]
我现在用的是这个1.2.5的版本，还是存在这个问题，没有更新最新的代码吗？

**Comment by pangchao21** [comment]
发现了关键问题，let scrollTop = tableRef.querySelector('.drag-tree-table-body').scrollTop;

**Comment by pangchao21** [comment]
这个scrollTop一直为0

**Comment by ColdDay** [comment]
> 这个scrollTop一直为0

你加fixed固定表头的属性了嘛

**Comment by ColdDay** [comment]
> 这个scrollTop一直为0

你把项目拉下来，npm i && npm run dev跑起来看看，我这边测试是OK的

**Comment by linvic** [comment]
你好，我1.2.5版本，同样出现这个问题

**Comment by linvic** [comment]
好像必须fixed才不会出现这个问题吗

**Comment by pangchao21** [comment]
你检查下父元素是不是有overflow这个属性了，这个也会影响到

**Comment by linvic** [comment]
> 你检查下父元素是不是有overflow这个属性了，这个也会影响到

没有，试了下，确实需要设置fixed并且设置高度，才不会有那个问题

**Comment by IcarusSky** [comment]
![image](https://user-images.githubusercontent.com/25057405/63141940-373df200-c01a-11e9-8999-bc1aaa01c39b.png)
当所有的父节点都处于闭合状态，拖拽位置就是鼠标当前位置，
![image](https://user-images.githubusercontent.com/25057405/63141995-710ef880-c01a-11e9-896d-9ea8fa947554.png)
当有其他根节点没有闭合，就会出现这种情况

**Comment by IcarusSky** [comment]
嗯....当出现了滚动条，位置就会出问题

**Comment by pangchao21** [comment]
检查下父级元素有没出现overflow，去掉再重试

**Comment by IcarusSky** [comment]
@pangchao21 嗯嗯  我明白怎么回事了    谢谢
