### ISSUE TITLE
能否在columns里面添加一个参数用于控制表格标题的对齐方式？

### ISSUE THREAD

**Issue by FullOfVigour** [mafengwo/vue-drag-tree-table#41]
在一些特定场景下，如：第一列为selection，单元格居左对齐，且这个单元格的宽度特别宽的时候，视觉效果不是很好，此时希望可以让标题的对齐对应上单元格的对齐方式
![image](https://user-images.githubusercontent.com/25943199/66070323-adbf9080-e583-11e9-9078-3f6cda9bf6ba.png)

**Comment by FullOfVigour** [comment]
固定高度出现滚动条时居中会有问题

**Comment by FullOfVigour** [comment]
![image](https://user-images.githubusercontent.com/25943199/66446897-e88f6000-ea7e-11e9-897d-9f3743cf4c94.png)
![image](https://user-images.githubusercontent.com/25943199/66446942-0eb50000-ea7f-11e9-91a9-0c5b8c0b994b.png)
最新版还是会出现拖拽位置不对以偶尔无法拖拽的情况

**Comment by ColdDay** [comment]
> ![image](https://user-images.githubusercontent.com/25943199/66446897-e88f6000-ea7e-11e9-897d-9f3743cf4c94.png)
> ![image](https://user-images.githubusercontent.com/25943199/66446942-0eb50000-ea7f-11e9-91a9-0c5b8c0b994b.png)
> 最新版还是会出现拖拽位置不对以偶尔无法拖拽的情况

最新版2.0.1，增加了表头对齐单独设置，增加参数titleAlign即可控制
另外你说的设置高度对齐问题，可以增加fixed参数试下，
https://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4

**Comment by FullOfVigour** [comment]
> > ![image](https://user-images.githubusercontent.com/25943199/66446897-e88f6000-ea7e-11e9-897d-9f3743cf4c94.png)
> > ![image](https://user-images.githubusercontent.com/25943199/66446942-0eb50000-ea7f-11e9-91a9-0c5b8c0b994b.png)
> > 最新版还是会出现拖拽位置不对以偶尔无法拖拽的情况
> 
> 最新版2.0.1，增加了表头对齐单独设置，增加参数titleAlign即可控制
> 另外你说的设置高度对齐问题，可以增加fixed参数试下，
> https://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4

嗯嗯谢谢开发者大大，只不过固定定位并不符合我这个项目的需求设计，我这边的布局是顶部导航栏和左侧菜单栏是固定定位，然后右下的这块的内容区块，这个表格就在这个内容区块里面，然后这个内容区块也是固定定位，但是它是内部可滚动的，这个时候如果把表格也进行固定定位的话就和整个产品的设计不符了，不知道对于这种表格在局部滚动中出现拖拽不对的情况有没有什么解决方法？（上面说的固定定位就是定位属性为fixed，小白萌新不知道这个是不是叫固定定位，请见谅）

**Comment by ColdDay** [comment]
> > > ![image](https://user-images.githubusercontent.com/25943199/66446897-e88f6000-ea7e-11e9-897d-9f3743cf4c94.png)
> > > ![image](https://user-images.githubusercontent.com/25943199/66446942-0eb50000-ea7f-11e9-91a9-0c5b8c0b994b.png)
> > > 最新版还是会出现拖拽位置不对以偶尔无法拖拽的情况
> > 
> > 
> > 最新版2.0.1，增加了表头对齐单独设置，增加参数titleAlign即可控制
> > 另外你说的设置高度对齐问题，可以增加fixed参数试下，
> > https://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4
> 
> 嗯嗯谢谢开发者大大，只不过固定定位并不符合我这个项目的需求设计，我这边的布局是顶部导航栏和左侧菜单栏是固定定位，然后右下的这块的内容区块，这个表格就在这个内容区块里面，然后这个内容区块也是固定定位，但是它是内部可滚动的，这个时候如果把表格也进行固定定位的话就和整个产品的设计不符了，不知道对于这种表格在局部滚动中出现拖拽不对的情况有没有什么解决方法？（上面说的固定定位就是定位属性为fixed，小白萌新不知道这个是不是叫固定定位，请见谅）

https://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4

看下这个demo，不是你说那个意思，只是冻结表头而已
