### ISSUE TITLE
你好，是否可增加列宽可拖拉调整

### ISSUE THREAD

**Issue by wzq-git-first** [mafengwo/vue-drag-tree-table#42]
你好，是否可增加列宽可拖拉调整

**Comment by ColdDay** [comment]
> 你好，是否可增加列宽可拖拉调整

你好，组件2.0.1版本增加可拖拽调整功能。增加resize参数即可，具体可参照https://www.mofazhuan.com/2019/11/15/vue-drag-tree-table%20Demo/#%E5%8D%95%E5%85%83%E6%A0%BC%E5%AE%BD%E5%BA%A6%E8%B0%83%E6%95%B4
