### ISSUE TITLE
当isContainChildren: true，会有一个bug，修改如下

### ISSUE THREAD

**Issue by yangmagnum** [mafengwo/vue-drag-tree-table#47]
当isContainChildren: true, //是否勾选子节点，默认false，有一个bug，我已经修复，GitHub上没有找到你的项目，希望你也能修复下，在row.vue中，onCheckboxClick方法中，this.setAllCheckData这一行改为 this.setAllCheckData([model] || [], !!evt.target.checked)

**Comment by ColdDay** [comment]
> 当isContainChildren: true, //是否勾选子节点，默认false，有一个bug，我已经修复，GitHub上没有找到你的项目，希望你也能修复下，在row.vue中，onCheckboxClick方法中，this.setAllCheckData这一行改为 this.setAllCheckData([model] || [], !!evt.target.checked)
感谢，这块确实有问题，我今天会修复一下，发一个新版

**Comment by ColdDay** [comment]
2.0.5版本修复```isContainChildren:true``` 导致选择数据错误
