### ISSUE TITLE
行展开问题

### ISSUE THREAD

**Issue by rockPrince** [mafengwo/vue-drag-tree-table#5]
你好 某一行有lists属性 但不写open属性 则无法展开 不知道这是个bug还是特意做的  :)

**Comment by ColdDay** [comment]
应该是个bug，我改一下，open字段不写默认折叠，感谢你的反馈，我会尽快更新npm版本修复这个问题

**Comment by zhuangyuxuan** [comment]
拖拽参数会不会有问题 返回LIST 那后台要更新全表吗

**Comment by ColdDay** [comment]
open改为非必要参数，默认折叠，修复版本1.2.0

**Comment by ColdDay** [comment]
> 你好 某一行有lists属性 但不写open属性 则无法展开 不知道这是个bug还是特意做的 :)

open改为非必要参数，默认折叠，修复版本1.2.0
