### ISSUE TITLE
scrollbar is not working properly with the plugin

### ISSUE THREAD

**Issue by munnabhaims** [mafengwo/vue-drag-tree-table#9]
Hi, 
We have much data in the page and made the header to be stay on the page always.  Also, we disabled the page scrollbar and used the scrollbar at the div level only. This time, drag and drop functionality is not working.  i noticed that plugin is considering page level X and Y coordinates to drop the element.   can you  fix this issue in the plugin?

Thanks

**Comment by ColdDay** [comment]
> Hi,
> We have much data in the page and made the header to be stay on the page always. Also, we disabled the page scrollbar and used the scrollbar at the div level only. This time, drag and drop functionality is not working. i noticed that plugin is considering page level X and Y coordinates to drop the element. can you fix this issue in the plugin?
> 
> Thanks

I have fixed the problem, https://github.com/mafengwo/vue-drag-tree-table/commit/a6ce47fa3bc2e06f2e2ae5e47c811d7dfed20768

Try it this way
```
<div style="overflow:scroll;height:500px">
<dragTreeTable :data="treeData" :onDrag="onTreeDataChange" :isdraggable="true"></dragTreeTable>
</div>
```

**Comment by munnabhaims** [comment]
Thanks for the providing the solution. your solution worked partially.  Still drag tree table  columns are moving up. it should be stick to the  on top of table.

**Comment by ColdDay** [comment]
> i have the same issue ,about the top of the table ,can't sticking to the on top of table.

You mean you need to support a fixed header, right?

**Comment by ColdDay** [comment]
hi
Version 1.2.4 already supports fixed headers，The method of use is as follows.

```html
<dragTreeTable
:data="treeData"
:onDrag="onTreeDataChange"
:fixed="true"
:height="300"
:isdraggable="true"></dragTreeTable>
```
